name: Test and Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install

      - name: Run tests with pytest
        run: python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Navigate to the project directory on your droplet
            cd /root/smash-discord-bot

            # Pull the latest code from the main branch
            git pull origin main

            # Install/update Python dependencies into the virtual environment
            ./.venv/bin/pip install -r requirements.txt
            
            # Install Playwright's browser binaries
            ./.venv/bin/playwright install

            # Restart the bot application using pm2
            pm2 restart smash-discord-bot
