# .github/workflows/deploy.yml

name: Deploy Discord Bot

# This action runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
# remove steps for initial commit to droplet
